import { Buffer } from 'node:buffer'
import { xdr, scValToNative } from '@stellar/stellar-sdk'
import { 
  ParsedEvent, 
  EventType, 
  VaultEventPayload, 
  MilestoneEventPayload, 
  ValidationEventPayload 
} from '../types/horizonSync.js'

type DecodedPayload = Record<string, unknown>

/**
 * Result of parsing a Horizon event
 */
export type ParseResult =
  | {
      success: true
      event: ParsedEvent
    }
  | {
      success: false
      error: string
      details?: Record<string, unknown>
    }

/**
 * Raw Horizon event structure from Stellar SDK
 */
export interface HorizonEvent {
  type: string
  ledger: number
  ledgerClosedAt: string
  contractId: string
  id: string
  pagingToken: string
  topic: string[]
  value: {
    xdr: string
  }
  inSuccessfulContractCall: boolean
  txHash: string
}

function decodePayloadRecord(xdrData: string): DecodedPayload | null {
  const candidates = [xdrData]

  try {
    const decoded = Buffer.from(xdrData, 'base64').toString('utf8')
    if (decoded && decoded !== xdrData) {
      candidates.push(decoded)
    }
  } catch {
    // Ignore invalid base64 and fall back to direct JSON parsing.
  }

  for (const candidate of candidates) {
    try {
      const parsed = JSON.parse(candidate) as unknown
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return parsed as DecodedPayload
      }
    } catch {
      // Try the next candidate.
    }
  }

  return null
}

function decodeScValRecord(xdrData: string, context: string): DecodedPayload | null {
  try {
    const scVal = xdr.ScVal.fromXDR(xdrData, 'base64')
    const nativeVal = scValToNative(scVal)
    if (nativeVal && typeof nativeVal === 'object' && !Array.isArray(nativeVal)) {
      return nativeVal as DecodedPayload
    }
    console.error(`${context} payload did not decode to an object`)
    return null
  } catch (error) {
    console.error(`Error parsing ${context} payload XDR:`, error)
    return null
  }
}

// UUID v4 (and general UUID) regex used to validate backend-generated vault ids
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

function isValidVaultId(id: string): boolean {
  return UUID_REGEX.test(id)
}


function readStringField(record: DecodedPayload, key: string): string | undefined {
  const value = record[key]
  return typeof value === 'string' ? value : undefined
}

function readDateField(record: DecodedPayload, key: string): Date | undefined {
  const value = record[key]

  if (value instanceof Date) {
    return Number.isNaN(value.getTime()) ? undefined : value
  }

  if (typeof value === 'string' || typeof value === 'number') {
    const parsed = new Date(value)
    return Number.isNaN(parsed.getTime()) ? undefined : parsed
  }

  return undefined
}

/**
 * Validates vault_created event payload
 * 
 * @param payload - The vault event payload to validate
 * @returns Error message if validation fails, null if valid
 */
function validateVaultCreatedPayload(payload: VaultEventPayload): string | null {
  if (!payload.vaultId || typeof payload.vaultId !== 'string') {
    return 'Missing or invalid vaultId field'
  }
  // Validate vaultId format (must be a UUID generated by the backend)
  if (!isValidVaultId(payload.vaultId)) {
    return 'vaultId must be a valid UUID'
  }
  
  if (!payload.creator || typeof payload.creator !== 'string') {
    return 'Missing or invalid creator field'
  }
  
  if (!payload.amount || typeof payload.amount !== 'string') {
    return 'Missing or invalid amount field'
  }
  
  // Validate amount is a valid decimal number
  if (isNaN(parseFloat(payload.amount))) {
    return 'Amount must be a valid decimal number'
  }
  
  if (!payload.startTimestamp || !(payload.startTimestamp instanceof Date)) {
    return 'Missing or invalid startTimestamp field'
  }
  
  if (!payload.endTimestamp || !(payload.endTimestamp instanceof Date)) {
    return 'Missing or invalid endTimestamp field'
  }
  
  if (!payload.successDestination || typeof payload.successDestination !== 'string') {
    return 'Missing or invalid successDestination field'
  }
  
  if (!payload.failureDestination || typeof payload.failureDestination !== 'string') {
    return 'Missing or invalid failureDestination field'
  }
  
  return null
}

/**
 * Validates vault status event payload
 * 
 * @param payload - The vault event payload to validate
 * @returns Error message if validation fails, null if valid
 */
function validateVaultStatusPayload(payload: VaultEventPayload): string | null {
  if (!payload.vaultId || typeof payload.vaultId !== 'string') {
    return 'Missing or invalid vaultId field'
  }
  if (!isValidVaultId(payload.vaultId)) {
    return 'vaultId must be a valid UUID'
  }
  
  if (!payload.status || typeof payload.status !== 'string') {
    return 'Missing or invalid status field'
  }
  
  const validStatuses = ['completed', 'failed', 'cancelled']
  if (!validStatuses.includes(payload.status)) {
    return `Invalid status value: ${payload.status}. Must be one of: ${validStatuses.join(', ')}`
  }
  
  return null
}

/**
 * Parses vault event payload from XDR data
 * 
 * @param eventType - The type of vault event
 * @param xdrData - Base64 encoded XDR data
 * @returns VaultEventPayload or null if parsing fails
 */
function parseVaultPayload(
  eventType: EventType,
  xdrData: string
): VaultEventPayload | null {
  // Try JSON decoding first (test fixtures and fallback path)
  const decoded = decodePayloadRecord(xdrData)

  const nativeVal = decoded ?? decodeScValRecord(xdrData, 'vault')
  if (!nativeVal) return null

  const vaultId = readStringField(nativeVal, 'vaultId') ??
    readStringField(nativeVal, 'vault_id')

  let payload: VaultEventPayload

  switch (eventType) {
    case 'vault_created': {
      payload = {
        vaultId,
        creator: readStringField(nativeVal, 'creator'),
        amount: nativeVal.amount == null ? undefined : nativeVal.amount.toString(),
        startTimestamp: readDateField(nativeVal, 'startTimestamp') ??
          readDateField(nativeVal, 'start_timestamp') ??
          readDateField(nativeVal, 'start_date'),
        endTimestamp: readDateField(nativeVal, 'endTimestamp') ??
          readDateField(nativeVal, 'end_timestamp') ??
          readDateField(nativeVal, 'end_date'),
        successDestination: readStringField(nativeVal, 'successDestination') ??
          readStringField(nativeVal, 'success_destination'),
        failureDestination: readStringField(nativeVal, 'failureDestination') ??
          readStringField(nativeVal, 'failure_destination'),
        status: 'active'
      } as VaultEventPayload
      const createdError = validateVaultCreatedPayload(payload)
      if (createdError) {
        console.error(`Vault created validation error: ${createdError}`)
        return null
      }
      return payload
    }

    case 'vault_completed':
    case 'vault_failed':
    case 'vault_cancelled': {
      payload = {
        vaultId,
        status: (readStringField(nativeVal, 'status') ||
          eventType.replace('vault_', '')) as VaultEventPayload['status']
      }
      const statusError = validateVaultStatusPayload(payload)
      if (statusError) {
        console.error(`Vault status validation error: ${statusError}`)
        return null
      }
      // Return the validated status payload. Previously this case fell through
      // to `default` and returned null, so valid status events never parsed.
      return payload
    }

    default:
      return null
  }
}

/**
 * Validates milestone_created event payload
 * 
 * @param payload - The milestone event payload to validate
 * @returns Error message if validation fails, null if valid
 */
function validateMilestonePayload(payload: MilestoneEventPayload): string | null {
  if (!payload.milestoneId || typeof payload.milestoneId !== 'string') {
    return 'Missing or invalid milestoneId field'
  }
  
  if (!payload.vaultId || typeof payload.vaultId !== 'string') {
    return 'Missing or invalid vaultId field'
  }
  if (!isValidVaultId(payload.vaultId)) {
    return 'vaultId must be a valid UUID'
  }
  
  if (!payload.title || typeof payload.title !== 'string') {
    return 'Missing or invalid title field'
  }
  
  if (!payload.targetAmount || typeof payload.targetAmount !== 'string') {
    return 'Missing or invalid targetAmount field'
  }
  
  // Validate targetAmount is a valid decimal number
  if (isNaN(parseFloat(payload.targetAmount))) {
    return 'targetAmount must be a valid decimal number'
  }
  
  if (!payload.deadline || !(payload.deadline instanceof Date)) {
    return 'Missing or invalid deadline field'
  }
  
  // Validate deadline is a valid date
  if (isNaN(payload.deadline.getTime())) {
    return 'deadline must be a valid date'
  }
  
  return null
}

/**
 * Parses milestone event payload from XDR data
 * 
 * @param xdrData - Base64 encoded XDR data
 * @returns MilestoneEventPayload or null if parsing fails
 */
function parseMilestonePayload(xdrData: string): MilestoneEventPayload | null {
  const decoded = decodePayloadRecord(xdrData)

  const nativeVal = decoded ?? decodeScValRecord(xdrData, 'milestone')
  if (!nativeVal) return null

  const payload: MilestoneEventPayload = {
    milestoneId: readStringField(nativeVal, 'milestoneId') ??
      readStringField(nativeVal, 'milestone_id'),
    vaultId: readStringField(nativeVal, 'vaultId') ??
      readStringField(nativeVal, 'vault_id'),
    title: readStringField(nativeVal, 'title'),
    description: readStringField(nativeVal, 'description') ?? '',
    targetAmount: nativeVal.targetAmount == null && nativeVal.amount == null
      ? undefined
      : (nativeVal.targetAmount ?? nativeVal.amount).toString(),
    deadline: readDateField(nativeVal, 'deadline') ??
      readDateField(nativeVal, 'due_date')
  } as MilestoneEventPayload

  const error = validateMilestonePayload(payload)
  if (error) {
    console.error(`Milestone validation error: ${error}`)
    return null
  }

  return payload
}

/**
 * Validates milestone_validated event payload
 * 
 * @param payload - The validation event payload to validate
 * @returns Error message if validation fails, null if valid
 */
function validateValidationPayload(payload: ValidationEventPayload): string | null {
  if (!payload.validationId || typeof payload.validationId !== 'string') {
    return 'Missing or invalid validationId field'
  }
  
  if (!payload.milestoneId || typeof payload.milestoneId !== 'string') {
    return 'Missing or invalid milestoneId field'
  }
  
  if (!payload.validatorAddress || typeof payload.validatorAddress !== 'string') {
    return 'Missing or invalid validatorAddress field'
  }
  
  if (!payload.validationResult || typeof payload.validationResult !== 'string') {
    return 'Missing or invalid validationResult field'
  }
  
  const validResults = ['approved', 'rejected', 'pending_review']
  if (!validResults.includes(payload.validationResult)) {
    return `Invalid validationResult value: ${payload.validationResult}. Must be one of: ${validResults.join(', ')}`
  }
  
  if (!payload.validatedAt || !(payload.validatedAt instanceof Date)) {
    return 'Missing or invalid validatedAt field'
  }
  
  // Validate validatedAt is a valid date
  if (isNaN(payload.validatedAt.getTime())) {
    return 'validatedAt must be a valid date'
  }
  
  return null
}

/**
 * Parses validation event payload from XDR data
 * 
 * @param xdrData - Base64 encoded XDR data
 * @returns ValidationEventPayload or null if parsing fails
 */
function parseValidationPayload(xdrData: string): ValidationEventPayload | null {
  const decoded = decodePayloadRecord(xdrData)

  const nativeVal = decoded ?? decodeScValRecord(xdrData, 'validation')
  if (!nativeVal) return null

  const payload: ValidationEventPayload = {
    validationId: readStringField(nativeVal, 'validationId') ??
      readStringField(nativeVal, 'validation_id'),
    milestoneId: readStringField(nativeVal, 'milestoneId') ??
      readStringField(nativeVal, 'milestone_id'),
    validatorAddress: readStringField(nativeVal, 'validatorAddress') ??
      readStringField(nativeVal, 'validator_address') ??
      readStringField(nativeVal, 'validator'),
    validationResult: (readStringField(nativeVal, 'validationResult') ??
      readStringField(nativeVal, 'validation_result') ??
      readStringField(nativeVal, 'result')) as ValidationEventPayload['validationResult'],
    evidenceHash: readStringField(nativeVal, 'evidenceHash') ??
      readStringField(nativeVal, 'evidence_hash') ?? '',
    validatedAt: readDateField(nativeVal, 'validatedAt') ??
      readDateField(nativeVal, 'validated_at') ??
      readDateField(nativeVal, 'timestamp')
  } as ValidationEventPayload

  const error = validateValidationPayload(payload)
  if (error) {
    console.error(`Validation event validation error: ${error}`)
    return null
  }

  return payload
}

/**
 * Routes event to appropriate payload parser based on event type
 * 
 * @param eventType - The type of event
 * @param xdrData - Base64 encoded XDR data
 * @returns Parsed payload or null if parsing fails
 */
function routeToPayloadParser(
  eventType: EventType,
  xdrData: string
): VaultEventPayload | MilestoneEventPayload | ValidationEventPayload | null {
  switch (eventType) {
    case 'vault_created':
    case 'vault_completed':
    case 'vault_failed':
    case 'vault_cancelled':
      return parseVaultPayload(eventType, xdrData)
    
    case 'milestone_created':
      return parseMilestonePayload(xdrData)
    
    case 'milestone_validated':
      return parseValidationPayload(xdrData)
    
    default:
      return null
  }
}

/**
 * Topic-to-event-type mapping for accountability_vault contract events.
 *
 * ## Symbol topic scheme
 *
 * All event topics emitted by the `accountability_vault` contract are
 * `soroban_sdk::Symbol` values (not `String`).  When decoded from XDR via
 * `scValToNative` they become plain JavaScript strings, so the mapping below
 * works transparently for both on-chain and off-chain consumers.
 *
 * Short topics (? 9 chars) use `symbol_short!` on the Rust side; longer
 * topics use `Symbol::new`.  The decoded string value is identical either way.
 *
 * Contract ? parser topic mapping
 * ?????????????????????????????????????????????????????????????????????????????
 * On-chain Symbol topic       Parser EventType (or handled inline)
 * ?????????????????????????????????????????????????????????????????????????????
 * vault_created               vault_created
 * vault_staked                vault_staked        (informational, no DB write)
 * milestone_checked_in        milestone_checked_in (informational)
 * deadline_extended           deadline_extended   (informational)
 * vault_slashed               vault_failed
 * vault_completed             vault_completed
 * vault_cancelled             vault_cancelled
 * vault_withdrawn             vault_cancelled     (withdrawal = cancelled state)
 * vault_paused                vault_paused        (informational)
 * vault_unpaused              vault_unpaused      (informational)
 * milestone_claimed           milestone_created   (partial-release, informational)
 * ?????????????????????????????????????????????????????????????????????????????
 *
 * Sources for check_in `source` topic:
 *   symbol_short!("oracle")    ? "oracle"
 *   symbol_short!("verifier")  ? "verifier"
 */

/**
 * Parses a Horizon event and extracts metadata and payload
 * 
 * @param rawEvent - Raw event from Horizon API
 * @returns ParseResult with success/failure and parsed event or error details
 */
export function parseHorizonEvent(rawEvent: HorizonEvent): ParseResult {
  try {
    // Validate required fields
    if (!rawEvent.txHash) {
      return {
        success: false,
        error: 'Missing transaction hash',
        details: { rawEvent }
      }
    }

    if (!rawEvent.id) {
      return {
        success: false,
        error: 'Missing event id',
        details: { rawEvent }
      }
    }

    if (typeof rawEvent.ledger !== 'number') {
      return {
        success: false,
        error: 'Missing or invalid ledger number',
        details: { rawEvent }
      }
    }

    // Extract event index from the event id (format: "txHash-index")
    const eventIndexMatch = rawEvent.id.match(/-(\d+)$/)
    if (!eventIndexMatch) {
      return {
        success: false,
        error: 'Could not extract event index from event id',
        details: { eventId: rawEvent.id }
      }
    }
    const eventIndex = parseInt(eventIndexMatch[1], 10)

    // Generate event_id in format {transaction_hash}:{event_index}
    const eventId = `${rawEvent.txHash}:${eventIndex}`

    // Extract event type from topic (first element)
    if (!rawEvent.topic || rawEvent.topic.length === 0) {
      return {
        success: false,
        error: 'Missing event topic',
        details: { rawEvent }
      }
    }

    // Normalise contract Symbol topics to the canonical EventType used by the
    // parser.  Symbol values decoded from XDR are plain strings, so this map
    // covers both the new Symbol-topic contract and any legacy String-topic
    // events still in the event stream.
    const TOPIC_ALIAS: Record<string, EventType> = {
      // Direct pass-throughs
      vault_created:           'vault_created',
      vault_completed:         'vault_completed',
      vault_cancelled:         'vault_cancelled',
      milestone_created:       'milestone_created',
      milestone_validated:     'milestone_validated',
      settlement_summary:      'settlement_summary',
      // Aliases: contract emits these Symbol topics ? mapped EventType
      vault_slashed:           'vault_failed',    // slash = failure destination
      vault_withdrawn:         'vault_cancelled', // withdraw = cancelled state
      vault_failed:            'vault_failed',    // explicit legacy alias
    }

    const rawTopic = rawEvent.topic[0]
    const eventType: EventType | undefined = TOPIC_ALIAS[rawTopic] as EventType | undefined

    // Informational-only topics that do not map to a DB-persisted EventType are
    // acknowledged and silently skipped rather than returned as parse errors.
    const INFORMATIONAL_TOPICS = new Set([
      'vault_staked',
      'milestone_checked_in',
      'deadline_extended',
      'vault_paused',
      'vault_unpaused',
      'milestone_claimed',
    ])

    if (!eventType) {
      if (INFORMATIONAL_TOPICS.has(rawTopic)) {
        return {
          success: false,
          error: `Informational topic skipped: ${rawTopic}`,
          details: { rawTopic }
        }
      }
      return {
        success: false,
        error: `Unknown event type: ${rawTopic}`,
        details: { eventType: rawTopic, validTypes: Object.keys(TOPIC_ALIAS) }
      }
    }

    // Route to appropriate payload parser based on event type
    const payload = routeToPayloadParser(eventType, rawEvent.value.xdr)
    
    if (!payload) {
      return {
        success: false,
        error: `Failed to parse payload for event type: ${eventType}`,
        details: { eventType, xdr: rawEvent.value.xdr }
      }
    }

    // Create parsed event with extracted payload
    const parsedEvent: ParsedEvent = {
      eventId,
      transactionHash: rawEvent.txHash,
      eventIndex,
      ledgerNumber: rawEvent.ledger,
      eventType,
      payload
    }

    return {
      success: true,
      event: parsedEvent
    }
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown parsing error',
      details: { error }
    }
  }
}
