/**
 * Milestone repository — soft-delete and verifier-assignment tests.
 *
 * These tests pin the query contract for the milestone repository so that a
 * regression that returns soft-deleted rows or leaks a milestone to the wrong
 * verifier cannot ship silently.  Issue #734.
 *
 *   - Default milestone reads exclude soft-deleted rows (`deleted_at IS NULL`).
 *   - Verifier-assigned queries return only milestones where
 *     `verifier_user_id = $verifier`.
 *   - The `verifier_user_id` linkage added by
 *     `db/migrations/20260428140504_add_verifier_user_id_to_milestones.cjs`
 *     is honoured.
 *   - Soft-delete followed by restore is a clean round-trip.
 *
 * The suite runs against the project test DB harness (PostgreSQL via
 * `setupTestDatabase`).  When `DATABASE_URL` is not set the suite is skipped.
 */

import type { Knex } from 'knex'
import { beforeAll, afterAll, beforeEach, describe, expect, it } from '@jest/globals'
import { MilestoneRepository } from './milestoneRepository.js'
import {
  cleanAllTables,
  setupTestDatabase,
  teardownTestDatabase,
} from '../tests/helpers/testDatabase.js'

// ---------------------------------------------------------------------------
// Harness availability gate
// ---------------------------------------------------------------------------

// Read once at module-load (registration time).  jest's `it.skip` decision
// made here is honored for the whole run; we intentionally do NOT depend on
// a beforeAll-computed flag for this because the registration / execution
// ordering otherwise silently turns every test into `it.skip`.
const skipSuite = !process.env.DATABASE_URL

let db: Knex | null = null
let repo: MilestoneRepository | null = null

beforeAll(async () => {
  if (skipSuite) {
    return
  }

  try {
    db = await setupTestDatabase()
    repo = new MilestoneRepository(db)
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('[milestoneRepository tests] setupTestDatabase failed:', err)
    throw err
  }
})

afterAll(async () => {
  if (db) {
    await teardownTestDatabase(db)
    db = null
  }
})

/**
 * Register a test as skipped when the suite is gated off (no DATABASE_URL),
 * otherwise register it normally.
 */
function itWhenDb(name: string, fn: () => Promise<void>): void {
  if (skipSuite) {
    it.skip(name, fn)
  } else {
    it(name, fn)
  }
}

function requireDb(): { db: Knex; repo: MilestoneRepository } {
  if (!db || !repo) {
    throw new Error('test database harness not initialised — see beforeAll logs')
  }
  return { db, repo }
}

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------
//
// We insert directly via the knex query builder rather than the project's
// `insertTestVault` / `insertTestMilestone` helpers because those helpers
// were written for an earlier schema snapshot.  Building the rows inline
// keeps these tests honest about which columns actually exist and avoids
// hiding schema drift behind a generic helper.

async function insertVault(db: Knex, vaultId: string): Promise<void> {
  await db('vaults').insert({
    id: vaultId,
    amount: '1000.0000000',
    start_date: new Date('2030-01-01T00:00:00Z'),
    end_date: new Date('2030-12-31T00:00:00Z'),
    verifier: 'GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    success_destination:
      'GSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCCESSSUCC',
    failure_destination:
      'GFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUREFAILUR',
    creator: 'GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    status: 'active',
  })
}

async function insertVerifier(db: Knex, userId: string): Promise<void> {
  await db.raw(
    `INSERT INTO verifiers (user_id, status, created_at)
     VALUES (?, 'approved', NOW())
     ON CONFLICT (user_id) DO NOTHING`,
    [userId],
  )
}

async function insertMilestone(
  db: Knex,
  milestoneId: string,
  vaultId: string,
  overrides: {
    title?: string
    verifierUserId?: string | null
    deletedAt?: Date | null
    sortOrder?: number
  } = {},
): Promise<void> {
  await db('milestones').insert({
    id: milestoneId,
    vault_id: vaultId,
    title: overrides.title ?? 'Test Milestone',
    description: 'auto-generated by milestoneRepository test fixture',
    target_amount: '500.0000000',
    current_amount: '0',
    deadline: new Date('2030-06-30T00:00:00Z'),
    status: 'pending',
    sort_order: overrides.sortOrder ?? 0,
    amount: '500.0000000',
    verifier_user_id: overrides.verifierUserId ?? null,
    deleted_at: overrides.deletedAt ?? null,
  })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('MilestoneRepository – soft-delete filtering (issue #734)', () => {
  beforeEach(async () => {
    if (!db) return
    await cleanAllTables(db)
  })

  itWhenDb('findById returns an active milestone', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertMilestone(db, 'ms-A', 'vault-A', { title: 'Alpha' })

    const row = await repo.findById('ms-A')

    expect(row).not.toBeNull()
    expect(row?.id).toBe('ms-A')
    expect(row?.title).toBe('Alpha')
    expect(row?.deleted_at).toBeNull()
  })

  itWhenDb('findById returns null for a soft-deleted milestone', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertMilestone(db, 'ms-A', 'vault-A', {
      deletedAt: new Date('2030-05-01T00:00:00Z'),
    })

    const row = await repo.findById('ms-A')

    expect(row).toBeNull()
  })

  itWhenDb('findById returns the soft-deleted row when includeDeleted=true', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    const deletedAt = new Date('2030-05-01T00:00:00Z')
    await insertMilestone(db, 'ms-A', 'vault-A', { deletedAt })

    const row = await repo.findById('ms-A', { includeDeleted: true })

    expect(row).not.toBeNull()
    expect(row?.id).toBe('ms-A')
    expect(row?.deleted_at).toEqual(deletedAt)
  })

  itWhenDb('findById returns null for an unknown id', async () => {
    const { repo } = requireDb()

    const row = await repo.findById('ms-does-not-exist')

    expect(row).toBeNull()
  })

  itWhenDb('softDelete sets deleted_at and findById then returns null', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertMilestone(db, 'ms-A', 'vault-A')

    const ok = await repo.softDelete('ms-A', new Date('2030-08-01T00:00:00Z'))
    expect(ok).toBe(true)

    expect(await repo.findById('ms-A')).toBeNull()
    expect(
      (await repo.findById('ms-A', { includeDeleted: true }))?.deleted_at,
    ).not.toBeNull()
  })

  itWhenDb('softDelete is idempotent — second call returns false', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertMilestone(db, 'ms-A', 'vault-A')

    expect(await repo.softDelete('ms-A', new Date('2030-08-01T00:00:00Z'))).toBe(true)
    expect(await repo.softDelete('ms-A', new Date('2030-08-02T00:00:00Z'))).toBe(false)
  })

  itWhenDb('softDelete on unknown id returns false', async () => {
    const { repo } = requireDb()

    expect(await repo.softDelete('ms-missing')).toBe(false)
  })

  itWhenDb('restore clears deleted_at and the milestone becomes visible again', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertMilestone(db, 'ms-A', 'vault-A')

    expect(await repo.softDelete('ms-A', new Date('2030-08-01T00:00:00Z'))).toBe(true)
    expect(await repo.findById('ms-A')).toBeNull()

    expect(await repo.restore('ms-A')).toBe(true)
    const row = await repo.findById('ms-A')
    expect(row).not.toBeNull()
    expect(row?.deleted_at).toBeNull()
  })

  itWhenDb('restore is a no-op on an already-active milestone', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertMilestone(db, 'ms-A', 'vault-A')

    expect(await repo.restore('ms-A')).toBe(false)
    expect(await repo.findById('ms-A')).not.toBeNull()
  })

  itWhenDb('restore on unknown id returns false', async () => {
    const { repo } = requireDb()

    expect(await repo.restore('ms-missing')).toBe(false)
  })

  itWhenDb('deleted-then-restored milestone reappears in default reads', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertVerifier(db, 'verifier-1')
    await insertMilestone(db, 'ms-A', 'vault-A', {
      verifierUserId: 'verifier-1',
      sortOrder: 1,
    })
    await insertMilestone(db, 'ms-B', 'vault-A', { sortOrder: 2 })

    // sanity: both visible
    expect(await repo.findById('ms-A')).not.toBeNull()
    expect(await repo.findById('ms-B')).not.toBeNull()

    // soft delete ms-A
    expect(await repo.softDelete('ms-A', new Date('2030-09-01T00:00:00Z'))).toBe(true)

    // default read no longer includes it
    expect(await repo.findById('ms-A')).toBeNull()
    // admin-style read still includes it
    expect(
      await repo.findById('ms-A', { includeDeleted: true }),
    ).not.toBeNull()

    // restore it
    expect(await repo.restore('ms-A')).toBe(true)

    // back to default-visible
    const restored = await repo.findById('ms-A')
    expect(restored).not.toBeNull()
    expect(restored?.deleted_at).toBeNull()
    // the verifier_user_id linkage survived the round-trip
    expect(restored?.verifier_user_id).toBe('verifier-1')
  })
})

describe('MilestoneRepository – verifier-assignment queries (issue #734)', () => {
  beforeEach(async () => {
    if (!db) return
    await cleanAllTables(db)
  })

  itWhenDb('listForVerifier returns only milestones assigned to that verifier', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertVerifier(db, 'verifier-1')
    await insertVerifier(db, 'verifier-2')
    await insertVerifier(db, 'verifier-3')

    await insertMilestone(db, 'ms-A', 'vault-A', {
      verifierUserId: 'verifier-1',
      sortOrder: 1,
    })
    await insertMilestone(db, 'ms-B', 'vault-A', {
      verifierUserId: 'verifier-1',
      sortOrder: 2,
    })
    await insertMilestone(db, 'ms-C', 'vault-A', {
      verifierUserId: 'verifier-2',
      sortOrder: 3,
    })
    // unassigned (verifier_user_id IS NULL) — must not leak to anyone
    await insertMilestone(db, 'ms-D', 'vault-A', { sortOrder: 4 })

    const v1 = await repo.listForVerifier('verifier-1')
    expect(v1.map((m) => m.id)).toEqual(['ms-A', 'ms-B'])

    const v2 = await repo.listForVerifier('verifier-2')
    expect(v2.map((m) => m.id)).toEqual(['ms-C'])

    // verifier-3 has zero assignments
    const v3 = await repo.listForVerifier('verifier-3')
    expect(v3).toEqual([])

    // sanity: nothing leaked to a mis-routed verifier
    expect(v1.find((m) => m.id === 'ms-C')).toBeUndefined()
    expect(v1.find((m) => m.id === 'ms-D')).toBeUndefined()
  })

  itWhenDb('listForVerifier excludes soft-deleted milestones', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertVerifier(db, 'verifier-1')

    await insertMilestone(db, 'ms-A', 'vault-A', {
      verifierUserId: 'verifier-1',
      sortOrder: 1,
    })
    await insertMilestone(db, 'ms-B', 'vault-A', {
      verifierUserId: 'verifier-1',
      sortOrder: 2,
      deletedAt: new Date('2030-07-01T00:00:00Z'),
    })

    const visible = await repo.listForVerifier('verifier-1')
    expect(visible.map((m) => m.id)).toEqual(['ms-A'])

    const all = await repo.listForVerifier('verifier-1', { includeDeleted: true })
    expect(all.map((m) => m.id).sort()).toEqual(['ms-A', 'ms-B'])
  })

  itWhenDb('listForVerifier preserves the verifier_user_id linkage on every row', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertVerifier(db, 'verifier-1')

    await insertMilestone(db, 'ms-A', 'vault-A', {
      verifierUserId: 'verifier-1',
    })

    const rows = await repo.listForVerifier('verifier-1')
    expect(rows).toHaveLength(1)
    expect(rows[0].verifier_user_id).toBe('verifier-1')
  })

  itWhenDb('listForVerifier returns empty array for a verifier with zero assignments', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertVerifier(db, 'verifier-1')
    await insertVerifier(db, 'verifier-unused')

    // milestones exist, but none are assigned to verifier-unused
    await insertMilestone(db, 'ms-A', 'vault-A', {
      verifierUserId: 'verifier-1',
    })
    await insertMilestone(db, 'ms-B', 'vault-A', { sortOrder: 2 })

    expect(await repo.listForVerifier('verifier-unused')).toEqual([])
  })

  itWhenDb('listForVerifier returns empty array for an unknown verifier id', async () => {
    const { repo } = requireDb()

    expect(await repo.listForVerifier('does-not-exist')).toEqual([])
  })

  itWhenDb('findById and listForVerifier agree on assignment', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertVerifier(db, 'verifier-1')

    await insertMilestone(db, 'ms-A', 'vault-A', {
      verifierUserId: 'verifier-1',
    })
    await insertMilestone(db, 'ms-B', 'vault-A', {
      verifierUserId: 'verifier-1',
    })

    const assignments = await repo.listForVerifier('verifier-1')
    const ids = assignments.map((m) => m.id)

    for (const id of ids) {
      const row = await repo.findById(id)
      expect(row).not.toBeNull()
      expect(row?.verifier_user_id).toBe('verifier-1')
    }
  })

  itWhenDb('soft-delete then restore: listForVerifier visibility round-trip', async () => {
    const { db, repo } = requireDb()
    await insertVault(db, 'vault-A')
    await insertVerifier(db, 'verifier-1')
    await insertVerifier(db, 'verifier-2')

    await insertMilestone(db, 'ms-A', 'vault-A', {
      verifierUserId: 'verifier-1',
      sortOrder: 1,
    })
    await insertMilestone(db, 'ms-B', 'vault-A', {
      verifierUserId: 'verifier-1',
      sortOrder: 2,
    })
    await insertMilestone(db, 'ms-C', 'vault-A', {
      verifierUserId: 'verifier-2',
      sortOrder: 3,
    })

    // sanity
    expect((await repo.listForVerifier('verifier-1')).map((m) => m.id))
      .toEqual(['ms-A', 'ms-B'])

    // soft-delete ms-A scoped to verifier-1
    expect(await repo.softDelete('ms-A', new Date('2030-10-01T00:00:00Z'))).toBe(true)

    // verifier-1 sees only the remaining live assignment
    expect((await repo.listForVerifier('verifier-1')).map((m) => m.id))
      .toEqual(['ms-B'])
    // verifier-2's view is unaffected
    expect((await repo.listForVerifier('verifier-2')).map((m) => m.id))
      .toEqual(['ms-C'])
    // admin-style read on verifier-1 still surfaces the deleted one
    expect(
      (await repo.listForVerifier('verifier-1', { includeDeleted: true }))
        .map((m) => m.id).sort(),
    ).toEqual(['ms-A', 'ms-B'])

    // restore
    expect(await repo.restore('ms-A')).toBe(true)

    // round-trip: verifier-1 sees both again
    expect((await repo.listForVerifier('verifier-1')).map((m) => m.id))
      .toEqual(['ms-A', 'ms-B'])
  })
})
